//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTiet_SP()
        {
            this.KT_Gia_NhapXuat = new HashSet<KT_Gia_NhapXuat>();
            this.MuaHangs = new HashSet<MuaHang>();
            this.DanhMucs = new HashSet<DanhMuc>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string HangSX { get; set; }
        public string ManHinh { get; set; }
        public string BaoHanh { get; set; }
        public string Ram { get; set; }
        public string BoNhoTrong { get; set; }
        public string HeDieuHanh { get; set; }
        public string Pin { get; set; }
        public int SoSim { get; set; }
        public string NoiXuatXu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KT_Gia_NhapXuat> KT_Gia_NhapXuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuaHang> MuaHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
    }
}
