//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.MuaHangs = new HashSet<MuaHang>();
        }
    
        public string MaDonHang { get; set; }
        public string MaTK { get; set; }
        public string MaNV { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public Nullable<int> UuDai { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual Theodoi_NV Theodoi_NV { get; set; }
        public virtual ThongTinCaNhan ThongTinCaNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuaHang> MuaHangs { get; set; }
    }
}
