//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoDien
{
    using System;
    using System.Collections.Generic;
    
    public partial class KT_Gia_NhapXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KT_Gia_NhapXuat()
        {
            this.MuaHangs = new HashSet<MuaHang>();
        }
    
        public int ID_Gia { get; set; }
        public string MaSP { get; set; }
        public int GiaNhap { get; set; }
        public int GiaBan { get; set; }
        public System.DateTime NgayApDung { get; set; }
    
        public virtual ChiTiet_SP ChiTiet_SP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MuaHang> MuaHangs { get; set; }
    }
}
